import test from "node:test";
import assert from "node:assert/strict";
import { mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { GENERATED_AGENT_NOTICE, addGeneratedNotice, isSafeTargetPath, syncAgents } from "../extensions/agent-installer/core.ts";

test("adds generated notice after YAML frontmatter", () => {
  const content = "---\nname: addy-reviewer\n---\n\nBody\n";
  assert.equal(addGeneratedNotice(content), `---\nname: addy-reviewer\n---\n${GENERATED_AGENT_NOTICE}\n\nBody\n`);
});

test("target path safety stays inside target root", () => {
  assert.equal(isSafeTargetPath("/tmp/root", "/tmp/root/agent.md"), true);
  assert.equal(isSafeTargetPath("/tmp/root", "/tmp/root2/agent.md"), false);
});

test("sync writes changed agents and removes stale generated files", async () => {
  const root = await mkdtemp(join(tmpdir(), "addy-agent-sync-"));
  const source = join(root, "source");
  const target = join(root, "target");
  await mkdir(source);
  await mkdir(target);
  await writeFile(join(source, "addy-reviewer.md"), "---\nname: addy-reviewer\n---\n\nBody\n");
  await writeFile(join(target, "stale.md"), `${GENERATED_AGENT_NOTICE}\n\nstale\n`);

  const result = await syncAgents({ sourceRoot: source, targetRoot: target });
  assert.equal(result.written.length, 1);
  assert.equal(result.removed.length, 1);
  assert.match(await readFile(join(target, "addy-reviewer.md"), "utf8"), /generated by pi-addy-workflow/);

  const second = await syncAgents({ sourceRoot: source, targetRoot: target });
  assert.equal(second.unchanged.length, 1);
  assert.equal(second.written.length, 0);
});

test("sync preserves nested directories and does not remove user files", async () => {
  const root = await mkdtemp(join(tmpdir(), "addy-agent-sync-nested-"));
  const source = join(root, "source");
  const target = join(root, "target");
  await mkdir(join(source, "nested"), { recursive: true });
  await mkdir(target);
  await writeFile(join(source, "nested", "addy-nested.md"), "---\nname: addy-nested\n---\n\nBody\n");
  await writeFile(join(target, "user.md"), "user content\n");

  const result = await syncAgents({ sourceRoot: source, targetRoot: target });
  assert.equal(result.written.length, 1);
  assert.equal(result.removed.length, 0);
  assert.match(await readFile(join(target, "nested", "addy-nested.md"), "utf8"), /name: addy-nested/);
  assert.equal(await readFile(join(target, "user.md"), "utf8"), "user content\n");
});
