import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdir, mkdtemp, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { tmpdir } from 'node:os';
import {
  GENERATED_AGENT_NOTICE,
  addGeneratedNotice,
  defaultAgentTargetRoot,
  packageAgentSourceRoot,
  syncAgents,
} from '../extensions/agent-installer/core.ts';

test('adds generated notice after YAML frontmatter', () => {
  const content = '---\nname: addy-reviewer\n---\n\nBody\n';
  assert.equal(
    addGeneratedNotice(content),
    `---\nname: addy-reviewer\n---\n${GENERATED_AGENT_NOTICE}\n\nBody\n`,
  );
});

test('package agent source root decodes file URLs', () => {
  const packageRoot = join(tmpdir(), 'addy agent package');
  const extensionUrl = pathToFileURL(
    join(packageRoot, 'extensions', 'agent-installer.ts'),
  ).href;

  assert.equal(
    packageAgentSourceRoot(extensionUrl),
    join(packageRoot, 'agents'),
  );
});

test('targets the shared top-level agent directory', () => {
  assert.equal(
    defaultAgentTargetRoot('/tmp/home'),
    join('/tmp/home', '.pi', 'agent', 'agents'),
  );
});

test('sync writes changed agents and removes stale generated files', async () => {
  const root = await mkdtemp(join(tmpdir(), 'addy-agent-sync-'));
  const source = join(root, 'source');
  const target = join(root, 'target');
  await mkdir(source);
  await mkdir(target);
  await writeFile(
    join(source, 'addy-reviewer.md'),
    '---\nname: addy-reviewer\n---\n\nBody\n',
  );
  await writeFile(
    join(target, 'stale.md'),
    `${GENERATED_AGENT_NOTICE}\n\nstale\n`,
  );

  const result = await syncAgents({ sourceRoot: source, targetRoot: target });
  assert.equal(result.written.length, 1);
  assert.equal(result.removed.length, 1);
  assert.match(
    await readFile(join(target, 'addy-reviewer.md'), 'utf8'),
    /generated by pi-addy-workflow/,
  );

  const second = await syncAgents({ sourceRoot: source, targetRoot: target });
  assert.equal(second.unchanged.length, 1);
  assert.equal(second.written.length, 0);
});

test('sync preserves nested directories and does not remove user files', async () => {
  const root = await mkdtemp(join(tmpdir(), 'addy-agent-sync-nested-'));
  const source = join(root, 'source');
  const target = join(root, 'target');
  await mkdir(join(source, 'nested'), { recursive: true });
  await mkdir(target);
  await writeFile(
    join(source, 'nested', 'addy-nested.md'),
    '---\nname: addy-nested\n---\n\nBody\n',
  );
  await writeFile(join(target, 'user.md'), 'user content\n');

  const result = await syncAgents({ sourceRoot: source, targetRoot: target });
  assert.equal(result.written.length, 1);
  assert.equal(result.removed.length, 0);
  assert.match(
    await readFile(join(target, 'nested', 'addy-nested.md'), 'utf8'),
    /name: addy-nested/,
  );
  assert.equal(
    await readFile(join(target, 'user.md'), 'utf8'),
    'user content\n',
  );
});

test('sync removes stale generated agents from the legacy nested directory', async () => {
  const root = await mkdtemp(join(tmpdir(), 'addy-agent-sync-legacy-'));
  const source = join(root, 'source');
  const target = join(root, 'agents');
  const legacy = join(target, 'pi-addy-workflow');
  await mkdir(source);
  await mkdir(legacy, { recursive: true });
  await writeFile(
    join(source, 'addy-reviewer.md'),
    '---\nname: addy-reviewer\n---\n\nBody\n',
  );
  await writeFile(
    join(legacy, 'addy-reviewer.md'),
    `---\nname: addy-reviewer\n---\n${GENERATED_AGENT_NOTICE}\n\nBody\n`,
  );

  const result = await syncAgents({ sourceRoot: source, targetRoot: target });

  assert.equal(result.written.length, 1);
  assert.equal(result.removed.length, 1);
  assert.equal(result.removed[0], join(legacy, 'addy-reviewer.md'));
  await assert.rejects(readFile(join(legacy, 'addy-reviewer.md'), 'utf8'));
});
