import { lstat, mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve, sep } from "node:path";

export const GENERATED_AGENT_NOTICE = "<!-- generated by pi-addy-workflow agent-installer; edit package source instead -->";

export type AgentSyncResult = {
  written: string[];
  removed: string[];
  unchanged: string[];
};

export function defaultAgentTargetRoot(home = process.env.HOME ?? process.cwd()): string {
  return join(home, ".pi", "agent", "agents", "pi-addy-workflow");
}

export function isSafeTargetPath(targetRoot: string, candidate: string): boolean {
  const root = resolve(targetRoot);
  const target = resolve(candidate);
  return target === root || target.startsWith(`${root}/`);
}

export function addGeneratedNotice(markdown: string): string {
  if (markdown.includes(GENERATED_AGENT_NOTICE)) return markdown;

  if (markdown.startsWith("---\n")) {
    const closingIndex = markdown.indexOf("\n---", 4);
    if (closingIndex !== -1) {
      const frontmatterEnd = closingIndex + "\n---".length;
      const before = markdown.slice(0, frontmatterEnd);
      const after = markdown.slice(frontmatterEnd).replace(/^\n+/, "");
      return `${before}\n${GENERATED_AGENT_NOTICE}\n\n${after}`;
    }
  }

  return `${GENERATED_AGENT_NOTICE}\n\n${markdown}`;
}

export async function listMarkdownFiles(dir: string, base = dir): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const files: string[] = [];

  for (const entry of entries) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await listMarkdownFiles(path, base)));
    } else if (entry.isFile() && entry.name.endsWith(".md")) {
      files.push(relative(base, path));
    }
  }

  return files.sort();
}

async function assertNoSymlink(path: string): Promise<void> {
  try {
    if ((await lstat(path)).isSymbolicLink()) throw new Error(`Refusing to sync through symlink: ${path}`);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return;
    throw error;
  }
}

async function assertNoSymlinkPathComponents(root: string, candidate: string): Promise<void> {
  const relativePath = relative(root, candidate);
  if (!relativePath || relativePath.startsWith("..")) return;

  let current = root;
  for (const part of relativePath.split(sep).filter(Boolean)) {
    current = join(current, part);
    await assertNoSymlink(current);
  }
}

export async function syncAgents(options: { sourceRoot: string; targetRoot?: string }): Promise<AgentSyncResult> {
  const sourceRoot = resolve(options.sourceRoot);
  const targetRoot = resolve(options.targetRoot ?? defaultAgentTargetRoot());
  const result: AgentSyncResult = { written: [], removed: [], unchanged: [] };

  await mkdir(targetRoot, { recursive: true });
  await assertNoSymlink(targetRoot);

  const sourceFiles = await listMarkdownFiles(sourceRoot);
  const sourceSet = new Set(sourceFiles);

  for (const file of sourceFiles) {
    const source = join(sourceRoot, file);
    const target = join(targetRoot, file);
    if (!isSafeTargetPath(targetRoot, target)) throw new Error(`Unsafe target path: ${target}`);
    await assertNoSymlinkPathComponents(targetRoot, dirname(target));
    await mkdir(dirname(target), { recursive: true });
    await assertNoSymlinkPathComponents(targetRoot, target);

    const nextContent = addGeneratedNotice(await readFile(source, "utf8"));
    let previousContent: string | undefined;
    try {
      previousContent = await readFile(target, "utf8");
    } catch {
      previousContent = undefined;
    }

    if (previousContent === nextContent) {
      result.unchanged.push(target);
      continue;
    }

    await writeFile(target, nextContent, "utf8");
    result.written.push(target);
  }

  for (const file of await listMarkdownFiles(targetRoot)) {
    if (sourceSet.has(file)) continue;
    const staleTarget = join(targetRoot, file);
    if (!isSafeTargetPath(targetRoot, staleTarget)) throw new Error(`Unsafe stale target path: ${staleTarget}`);
    await assertNoSymlinkPathComponents(targetRoot, staleTarget);
    const staleContent = await readFile(staleTarget, "utf8");
    if (!staleContent.includes(GENERATED_AGENT_NOTICE)) continue;
    await rm(staleTarget, { force: true });
    result.removed.push(staleTarget);
  }

  return result;
}

export function packageAgentSourceRoot(importMetaUrl: string): string {
  return resolve(new URL("../agents", importMetaUrl).pathname);
}

export function relativeAgentSyncSummary(result: AgentSyncResult, targetRoot: string): string {
  const changed = result.written.length + result.removed.length;
  if (changed === 0) return "pi-addy-workflow agents already synced";
  return `pi-addy-workflow synced ${result.written.length} agent(s), removed ${result.removed.length} stale file(s) in ${relative(process.cwd(), targetRoot) || targetRoot}`;
}
