import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join, relative, resolve } from 'node:path';

export const GENERATED_AGENT_NOTICE =
  '<!-- generated by pi-addy-workflow agent-installer; edit package source instead -->';

export type AgentSyncResult = {
  written: string[];
  removed: string[];
  unchanged: string[];
};

export function defaultAgentTargetRoot(
  home = process.env.HOME ?? process.cwd(),
): string {
  return join(home, '.pi', 'agent', 'agents');
}

export function addGeneratedNotice(markdown: string): string {
  if (markdown.includes(GENERATED_AGENT_NOTICE)) return markdown;

  if (markdown.startsWith('---\n')) {
    const closingIndex = markdown.indexOf('\n---', 4);
    if (closingIndex !== -1) {
      const frontmatterEnd = closingIndex + '\n---'.length;
      const before = markdown.slice(0, frontmatterEnd);
      const after = markdown.slice(frontmatterEnd).replace(/^\n+/, '');
      return `${before}\n${GENERATED_AGENT_NOTICE}\n\n${after}`;
    }
  }

  return `${GENERATED_AGENT_NOTICE}\n\n${markdown}`;
}

export async function listMarkdownFiles(
  dir: string,
  base = dir,
): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const files: string[] = [];

  for (const entry of entries) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await listMarkdownFiles(path, base)));
    } else if (entry.isFile() && entry.name.endsWith('.md')) {
      files.push(relative(base, path));
    }
  }

  return files.sort();
}

export async function syncAgents(options: {
  sourceRoot: string;
  targetRoot?: string;
}): Promise<AgentSyncResult> {
  const sourceRoot = resolve(options.sourceRoot);
  const targetRoot = resolve(options.targetRoot ?? defaultAgentTargetRoot());
  const result: AgentSyncResult = { written: [], removed: [], unchanged: [] };

  await mkdir(targetRoot, { recursive: true });

  const sourceFiles = await listMarkdownFiles(sourceRoot);
  const sourceSet = new Set(sourceFiles);

  for (const file of sourceFiles) {
    const source = join(sourceRoot, file);
    const target = join(targetRoot, file);
    await mkdir(dirname(target), { recursive: true });

    const nextContent = addGeneratedNotice(await readFile(source, 'utf8'));
    let previousContent: string | undefined;
    try {
      previousContent = await readFile(target, 'utf8');
    } catch {
      previousContent = undefined;
    }

    if (previousContent === nextContent) {
      result.unchanged.push(target);
      continue;
    }

    await writeFile(target, nextContent, 'utf8');
    result.written.push(target);
  }

  for (const file of await listMarkdownFiles(targetRoot)) {
    if (sourceSet.has(file)) continue;
    const staleTarget = join(targetRoot, file);
    const staleContent = await readFile(staleTarget, 'utf8');
    if (!staleContent.includes(GENERATED_AGENT_NOTICE)) continue;
    await rm(staleTarget, { force: true });
    result.removed.push(staleTarget);
  }

  return result;
}

export function packageAgentSourceRoot(importMetaUrl: string): string {
  return resolve(fileURLToPath(new URL('../agents', importMetaUrl)));
}

export function relativeAgentSyncSummary(
  result: AgentSyncResult,
  targetRoot: string,
): string {
  const changed = result.written.length + result.removed.length;
  if (changed === 0) return 'pi-addy-workflow agents already synced';
  return `pi-addy-workflow synced ${result.written.length} agent(s), removed ${result.removed.length} stale file(s) in ${relative(process.cwd(), targetRoot) || targetRoot}`;
}
