import { constants } from 'node:fs';
import { access, chmod, mkdir, readFile, writeFile } from 'node:fs/promises';
import { spawn, type ChildProcess } from 'node:child_process';
import { delimiter, dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

export const GENERATED_DASHBOARD_SHIM_NOTICE =
  '# generated by pi-addy-workflow dashboard-installer; edit package source instead';
export const GENERATED_PROGRESS_SHIM_NOTICE =
  '# generated by pi-addy-workflow dashboard-installer; edit package source instead';

export type DashboardShimResult = {
  shimPath: string;
  binDir: string;
  changed: boolean;
  pathUpdated: boolean;
};

export function defaultDashboardBinDir(
  home = process.env.HOME ?? process.cwd(),
): string {
  return join(home, '.pi', 'agent', 'bin');
}

export function packageRoot(importMetaUrl: string): string {
  return resolve(fileURLToPath(new URL('..', importMetaUrl)));
}

export function dashboardBinSource(importMetaUrl: string): string {
  return join(packageRoot(importMetaUrl), 'bin', 'addy-dashboard.ts');
}

export function progressBinSource(importMetaUrl: string): string {
  return join(packageRoot(importMetaUrl), 'bin', 'addy-progress.ts');
}

function pathIncludes(
  dir: string,
  pathValue = process.env.PATH ?? '',
): boolean {
  return pathValue.split(delimiter).some((entry) => resolve(entry) === dir);
}

function executableShimContent(notice: string, sourcePath: string): string {
  return `#!/bin/sh\n${notice}\nexec node --experimental-strip-types ${JSON.stringify(sourcePath)} "$@"\n`;
}

export function dashboardShimContent(sourcePath: string): string {
  return executableShimContent(GENERATED_DASHBOARD_SHIM_NOTICE, sourcePath);
}

export function progressShimContent(sourcePath: string): string {
  return executableShimContent(GENERATED_PROGRESS_SHIM_NOTICE, sourcePath);
}

async function isExecutable(path: string): Promise<boolean> {
  try {
    await access(path, constants.X_OK);
    return true;
  } catch {
    return false;
  }
}

async function ensureShim(
  command: string,
  content: string,
  options: { binDir?: string; env?: NodeJS.ProcessEnv },
): Promise<DashboardShimResult> {
  const env = options.env ?? process.env;
  const binDir = resolve(options.binDir ?? defaultDashboardBinDir());
  const shimPath = join(binDir, command);
  const pathUpdated = !pathIncludes(binDir, env.PATH);
  if (pathUpdated) env.PATH = `${binDir}${delimiter}${env.PATH ?? ''}`;

  let previousContent: string | undefined;
  try {
    previousContent = await readFile(shimPath, 'utf8');
  } catch {
    previousContent = undefined;
  }

  const executable =
    previousContent === content && (await isExecutable(shimPath));
  if (executable) return { shimPath, binDir, changed: false, pathUpdated };

  await mkdir(dirname(shimPath), { recursive: true });
  await writeFile(shimPath, content, 'utf8');
  await chmod(shimPath, 0o755);
  return { shimPath, binDir, changed: true, pathUpdated };
}

export async function ensureDashboardShim(
  importMetaUrl: string,
  options: { binDir?: string; env?: NodeJS.ProcessEnv } = {},
): Promise<DashboardShimResult> {
  const sourcePath = dashboardBinSource(importMetaUrl);
  return ensureShim(
    'addy-dashboard',
    dashboardShimContent(sourcePath),
    options,
  );
}

export async function ensureProgressShim(
  importMetaUrl: string,
  options: { binDir?: string; env?: NodeJS.ProcessEnv } = {},
): Promise<DashboardShimResult> {
  const sourcePath = progressBinSource(importMetaUrl);
  return ensureShim('addy-progress', progressShimContent(sourcePath), options);
}

export function dashboardShimUsage(result: DashboardShimResult): string {
  const pathHint = result.pathUpdated
    ? ` Add ${result.binDir} to your shell PATH to use it outside Pi.`
    : '';
  return `Installed addy-dashboard. Open it with: addy-dashboard --project-path "$PWD".${pathHint}`;
}

export type DashboardCommandPlan = {
  serverArgs: string[];
  url: string;
  public: boolean;
};

export function planDashboardCommand(
  args: string[],
  options: { cwd?: string } = {},
): DashboardCommandPlan {
  const serverArgs = [...args];
  const publicIndex = serverArgs.indexOf('--public');
  const isPublic = publicIndex >= 0;
  if (isPublic) {
    serverArgs.splice(publicIndex, 1);
    if (!serverArgs.includes('--host') && !serverArgs.includes('-h'))
      serverArgs.push('--host', '0.0.0.0');
  }

  if (!serverArgs.includes('--project-path') && options.cwd)
    serverArgs.push('--project-path', options.cwd);

  const portIndex = serverArgs.findIndex(
    (arg) => arg === '--port' || arg === '-p',
  );
  const port = portIndex >= 0 ? serverArgs[portIndex + 1] : '3848';
  return { serverArgs, url: `http://127.0.0.1:${port}`, public: isPublic };
}

function openCommand(url: string): { command: string; args: string[] } {
  if (process.platform === 'darwin') return { command: 'open', args: [url] };
  if (process.platform === 'win32')
    return { command: 'cmd', args: ['/c', 'start', '', url] };
  return { command: 'xdg-open', args: [url] };
}

export function launchDashboardCommand(
  importMetaUrl: string,
  args: string[],
  options: {
    cwd?: string;
    spawnProcess?: typeof spawn;
  } = {},
): DashboardCommandPlan & { server: ChildProcess; opener: ChildProcess } {
  const plan = planDashboardCommand(args, options);
  const spawnProcess = options.spawnProcess ?? spawn;
  const server = spawnProcess(
    process.execPath,
    [
      '--experimental-strip-types',
      dashboardBinSource(importMetaUrl),
      ...plan.serverArgs,
    ],
    { detached: true, stdio: 'ignore' },
  );
  server.on('error', () => {});
  server.unref();

  const openerCommand = openCommand(plan.url);
  const opener = spawnProcess(openerCommand.command, openerCommand.args, {
    detached: true,
    stdio: 'ignore',
  });
  opener.on('error', () => {});
  opener.unref();

  return { ...plan, server, opener };
}
