import { constants } from 'node:fs';
import { access, chmod, mkdir, readFile, writeFile } from 'node:fs/promises';
import { delimiter, dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

export const GENERATED_DASHBOARD_SHIM_NOTICE =
  '# generated by pi-addy-workflow dashboard-installer; edit package source instead';

export type DashboardShimResult = {
  shimPath: string;
  binDir: string;
  changed: boolean;
  pathUpdated: boolean;
};

export function defaultDashboardBinDir(
  home = process.env.HOME ?? process.cwd(),
): string {
  return join(home, '.pi', 'agent', 'bin');
}

export function packageRoot(importMetaUrl: string): string {
  return resolve(fileURLToPath(new URL('..', importMetaUrl)));
}

export function dashboardBinSource(importMetaUrl: string): string {
  return join(packageRoot(importMetaUrl), 'bin', 'addy-dashboard.ts');
}

function pathIncludes(
  dir: string,
  pathValue = process.env.PATH ?? '',
): boolean {
  return pathValue.split(delimiter).some((entry) => resolve(entry) === dir);
}

export function dashboardShimContent(sourcePath: string): string {
  return `#!/bin/sh\n${GENERATED_DASHBOARD_SHIM_NOTICE}\nexec node --experimental-strip-types ${JSON.stringify(sourcePath)} "$@"\n`;
}

async function isExecutable(path: string): Promise<boolean> {
  try {
    await access(path, constants.X_OK);
    return true;
  } catch {
    return false;
  }
}

export async function ensureDashboardShim(
  importMetaUrl: string,
  options: { binDir?: string; env?: NodeJS.ProcessEnv } = {},
): Promise<DashboardShimResult> {
  const env = options.env ?? process.env;
  const binDir = resolve(options.binDir ?? defaultDashboardBinDir());
  const shimPath = join(binDir, 'addy-dashboard');
  const sourcePath = dashboardBinSource(importMetaUrl);
  const nextContent = dashboardShimContent(sourcePath);

  const pathUpdated = !pathIncludes(binDir, env.PATH);
  if (pathUpdated) env.PATH = `${binDir}${delimiter}${env.PATH ?? ''}`;

  let previousContent: string | undefined;
  try {
    previousContent = await readFile(shimPath, 'utf8');
  } catch {
    previousContent = undefined;
  }

  const executable =
    previousContent === nextContent && (await isExecutable(shimPath));
  if (executable) return { shimPath, binDir, changed: false, pathUpdated };

  await mkdir(dirname(shimPath), { recursive: true });
  await writeFile(shimPath, nextContent, 'utf8');
  await chmod(shimPath, 0o755);
  return { shimPath, binDir, changed: true, pathUpdated };
}

export function dashboardShimUsage(result: DashboardShimResult): string {
  const pathHint = result.pathUpdated
    ? ` Add ${result.binDir} to your shell PATH to use it outside Pi.`
    : '';
  return `Installed addy-dashboard. Open it with: addy-dashboard --project-path "$PWD".${pathHint}`;
}
